<?php
echo "# vim:ft=kitty\n";
echo "\n";
echo "## name: $theme_name Light\n";
echo "## author: $theme_author (https://github.com/$theme_author_github_name)\n";
echo "## license: $theme_license\n";
echo "## upstream: $theme_upstream_url-light.conf\n";
echo "## blurb: $theme_description\n";
echo "\n";
echo "\n";
echo "#: The basic colors\n";
echo "\n";
echo "foreground $base02\n";
echo "background $base07\n";
echo "selection_foreground $base02\n";
echo "selection_background $base05\n";
echo "\n";
echo "\n";
echo "#: Cursor colors\n";
echo "\n";
echo "cursor $base02\n";
echo "cursor_text_color $base07\n";
echo "\n";
echo "\n";
echo "#: URL underline color when hovering with mouse\n";
echo "\n";
echo "url_color $base0E\n";
echo "\n";
echo "\n";
echo "#: kitty window border colors and terminal bell colors\n";
echo "\n";
echo "active_border_color $base05\n";
echo "inactive_border_color $base07\n";
echo "bell_border_color $base09\n";
echo "visual_bell_color none\n";
echo "\n";
echo "\n";
echo "#: OS Window titlebar colors\n";
echo "\n";
echo "wayland_titlebar_color system\n";
echo "macos_titlebar_color system\n";
echo "\n";
echo "\n";
echo "#: Tab bar colors\n";
echo "\n";
echo "active_tab_foreground $base01\n";
echo "active_tab_background $base07\n";
echo "inactive_tab_foreground $base02\n";
echo "inactive_tab_background $base06\n";
echo "tab_bar_background $base05\n";
echo "tab_bar_margin_color none\n";
echo "\n";
echo "\n";
echo "#: Colors for marks (marked text in the terminal)\n";
echo "\n";
echo "mark1_foreground $base07\n";
echo "mark1_background $base01\n";
echo "mark2_foreground $base07\n";
echo "mark2_background $base0E\n";
echo "mark3_foreground $base07\n";
echo "mark3_background $base0F\n";
echo "\n";
echo "\n";
echo "#: The basic 16 colors\n";
echo "\n";
echo "#: black\n";
echo "color0 $base00\n";
echo "color8 $base03\n";
echo "\n";
echo "#: red\n";
echo "color1 $base08\n";
echo "color9 $base09\n";
echo "\n";
echo "#: green\n";
echo "color2 $base0B\n";
echo "color10 $base01\n";
echo "\n";
echo "#: yellow\n";
echo "color3 $base0A\n";
echo "color11 $base02\n";
echo "\n";
echo "#: blue\n";
echo "color4 $base0D\n";
echo "color12 $base04\n";
echo "\n";
echo "#: magenta\n";
echo "color5 $base0E\n";
echo "color13 $base06\n";
echo "\n";
echo "#: cyan\n";
echo "color6 $base0C\n";
echo "color14 $base0F\n";
echo "\n";
echo "#: white\n";
echo "color7 $base05\n";
echo "color15 $base07\n";
